version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: unless-stopped

    ports:
      - "5672:5672"    # Puerto AMQP
      - "15672:15672"  # Interfaz web de administración

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network:
    driver: bridge